seed: 42
results_dir: results
run_id: C048
workload:
  type: BU
  ops_per_sec: 10
  read_ratio: null
access_pattern:
  type: hotspot
  hotspot_fraction: 0.05
  hotspot_share: 0.5
agents:
  count: 10
  group_mod: 5
context:
  size_tokens: 100
mcp:
  strategy: BC
  network_delay_ms: 5
  ttl_seconds: 60
  l1_capacity: 100
  l2_capacity: 1000
measurement:
  init_seconds: 5
  warmup_seconds: 10
  measure_seconds: 60
  cooldown_seconds: 10
  log_interval_seconds: 1
