seed: 42
results_dir: results
run_id: C421
workload:
  type: RH
  ops_per_sec: 10
  read_ratio: 0.8
access_pattern:
  type: uniform
agents:
  count: 10
  group_mod: 5
context:
  size_tokens: 2000
mcp:
  strategy: PD
  network_delay_ms: 5
  ttl_seconds: 60
  l1_capacity: 100
  l2_capacity: 1000
measurement:
  init_seconds: 5
  warmup_seconds: 10
  measure_seconds: 60
  cooldown_seconds: 10
  log_interval_seconds: 1
