seed: 42
results_dir: results
run_id: default

workload:
  type: RH  # RH | WH | BA | BU
  ops_per_sec: 10
  read_ratio: 0.8   # ignored for BU
  burst:
    enabled: false
    max_ops_per_sec: 20

access_pattern:
  type: zipf   # uniform | zipf | hotspot
  zipf_alpha: 0.99
  hotspot_fraction: 0.05
  hotspot_share: 0.5

agents:
  count: 10
  group_mod: 5

context:
  size_tokens: 500  # 100 | 500 | 2000

mcp:
  strategy: HA  # BC | PS | PD | HC | HA
  network_delay_ms: 5
  ttl_seconds: 60
  l1_capacity: 100
  l2_capacity: 1000

measurement:
  init_seconds: 5
  warmup_seconds: 30
  measure_seconds: 300
  cooldown_seconds: 10
  log_interval_seconds: 1
